#' Run site validation shiny app

#' Runs site validation shiny app embedded in UT IR tools package.

#' @param master_site_file Full path and filename of master site list as generated by autoValidateWQPsites function and manual site review application (.csv).
#' @param polygon_path Full path to folder containing BU, AU, and state of UT polygons.
#' @param edit_log_path Full path to folder containing site edit log.
#' @param reasons_flat_file Full patch and filename of flat site review/reject reasons exported by autoValidateWQPsites function.

#' @import shiny
#' @import raster
#' @import rhandsontable
#' @import mapview
#' @import mapedit
#' @import sf
#' @import sp
#' @import leaflet
#' @import shinyjs
#' @import V8
#' @import rgdal

#' @export
runSiteValApp=function(master_site_file,polygon_path,edit_log_path,reasons_flat_file){
	 master_site_file<<-master_site_file
	 polygon_path<<-polygon_path
	 edit_log_path<<-edit_log_path
	 reasons_flat_file<<-reasons_flat_file
	 shiny::runApp(system.file('siteValApp', package='irTools'))
	 rm(master_site_file)
	 rm(polygon_path)
	 rm(edit_log_path)
 	 rm(reasons_flat_file)

	 }
