#' Run site validation shiny app

#' Runs site validation shiny app embedded in UT IR tools package.

#' @param master_site_file Full path and filename of master site list as generated by autoValidateWQPsites function and manual site review application (.csv).
#' @param polygon_path Full path to folder containing BU, AU, and state of UT polygons.
#' @param edit_log_path Full path to folder containing site edit log.
#' @param reasons_flat_file Full patch and filename of flat site review/reject reasons exported by autoValidateWQPsites function.

#' @import shiny
#' @import raster
#' @import rhandsontable
#' @import mapview
#' @import mapedit
#' @import sf
#' @import sp
#' @import leaflet
#' @import shinyjs
#' @import V8
#' @import rgdal

#' @export
runSiteValApp=function(master_site_file,polygon_path,edit_log_path,reasons_flat_file){
   #master_site_file="P:\\WQ\\Integrated Report\\Automation_Development\\jake\\03site_validation\\wqp_master_site_file.csv"
	 #sites=read.csv(master_site_file)
	 #reasons_flat_file=-"P:\\WQ\\Integrated Report\\Automation_Development\\R_package\\demo\\02site_validation\\rev_rej_reasons.csv"
   print("WARNING: Ensure your reasons file and master site file come from the same iteration of the autoValidateWQPsites function.")
   master_site_file<<-master_site_file
	 polygon_path<<-polygon_path
	 edit_log_path<<-edit_log_path
	 reasons_flat_file<<-"P:\\WQ\\Integrated Report\\Automation_Development\\R_package\\demo\\02site_validation\\rev_rej_reasons.csv"
	 shiny::runApp(system.file('siteValApp', package='irTools'))
	 rm(master_site_file)
	 rm(polygon_path)
	 rm(edit_log_path)
 	 rm(reasons_flat_file)

	 }
