#' Run site validation shiny app

#' Runs site validation shiny app embedded in UT IR tools package.

#' @param master_site_file Full path and filename of master site list as generated by autoValidateWQPsites function and manual site review application (.csv).

#' @import shiny
#' @import raster
#' @import rhandsontable
#' @import mapview
#' @import mapedit
#' @import sf
#' @import sp
#' @import leaflet
#' @import shinyjs
#' @import V8
#' @import rgdal

#' @export
runSiteValApp=function(master_site_file,polygon_path,edit_log_path){
	 #master_site_file="P:\\WQ\\Integrated Report\\Automation_Development\\jake\\03site_validation\\wqp_master_site_file.csv"
	 #sites=read.csv(master_site_file)
	 master_site_file<<-master_site_file
	 polygon_path<<-polygon_path
	 edit_log_path<<-edit_log_path
	 shiny::runApp(system.file('siteValApp', package='irTools'))
	 rm(master_site_file)
	 rm(polygon_path)
	 rm(edit_log_path)
	 }
